# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZYEApd6QA5ZwNLcibTlf0Db3xqLQlGt
"""

n_epochs = 100
all_losses = []

for epoch in range(n_epochs):
    total_loss = 0

    for name_tensor, gender in dataloader:
        name_tensor = name_tensor.to(device)
        gender = gender.to(device)

        hidden = model.init_hidden()

        optimizer.zero_grad()

        output, hidden = model(name_tensor, hidden)
        loss = criterion(output, gender)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(dataloader)
    all_losses.append(avg_loss)

    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{n_epochs}], Loss: {avg_loss:.4f}')

plt.plot(all_losses)
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training Loss')
plt.show()

